services:
  backend:
    build: .
    ports:
      - "8000:8000"
    volumes:
      - ./proxy-list.txt:/app/proxy-list.txt
    healthcheck:
      test: ["CMD", "curl", "-f", "http://localhost:8000/docs"]
      interval: 30s
      timeout: 10s
      retries: 3
      start_period: 10s

  frontend:
    build: ./client
    ports:
      - "80:80"
    depends_on:
      backend:
        condition: service_healthy

networks:
  default:
    driver: bridge
